name: (main) populate webnovel volumes surrealdb

on:
  push:
    branches:
      - main
    paths:
      - "data/media/twi-webnovel-volumes.yaml"

jobs:
  populate-db:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        deno:
          - 1.26.2
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - name: populate database
        run: deno task surrealdb-populate-webnovel-volumes
        env:
          SURREALDB_URL: ${{ secrets.SURREALDB_URL }}
          SURREALDB_NAMESPACE: ${{ secrets.SURREALDB_NAMESPACE }}
          SURREALDB_DATABASE: ${{ secrets.SURREALDB_DATABASE }}
          SURREALDB_USERNAME: ${{ secrets.SURREALDB_USERNAME }}
          SURREALDB_PASSWORD: ${{ secrets.SURREALDB_PASSWORD }}
